#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 03
yabai -m config bottom_padding 03
yabai -m config left_padding 03
yabai -m config right_padding 03
yabai -m config window_gap 03
# yabai -m config external_bar all:0:0

# specific space settings
# yabai -m config --space 4 layout stack
# yabai -m config --space 7 layout stack

# display rules
yabai -m space 1 --display 1
yabai -m space 2 --display 1
yabai -m space 3 --display 1
yabai -m space 4 --display 1
yabai -m space 5 --display 1
yabai -m space 6 --display 2
yabai -m space 7 --display 2
yabai -m space 8 --display 2
yabai -m space 9 --display 2
yabai -m space 10 --display 2

# window rules
yabai -m rule --add app="^Chrome$" space=1
yabai -m rule --add app="^Code$" space=2
yabai -m rule --add app="Slack" space=3
yabai -m rule --add app="^iTerm2$" space=2
yabai -m rule --add app="Slack" title="^Slack.*Huddle$" space=6 manage=off
yabai -m rule --add app="^Figma$" space=5
yabai -m rule --add app="^WhatsApp$" space=9
yabai -m rule --add app="^Signal$" space=9
yabai -m rule --add app="^Telegram$" space=9
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^ImageOptim$" manage=off
yabai -m rule --add app="^Chromium$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^.*Preferences.*$" manage=off
yabai -m rule --add app="^.*Settings.*$" manage=off
yabai -m rule --add app="^Arc$" title="Daniel" manage=off
yabai -m rule --add app="Arc" title="Developer Tools" space=6
yabai -m rule --add title="^CleanMyMac$" manage=off
yabai -m rule --add title="^.*CleanShot.*$" manage=off
yabai -m rule --add title="^.*Photoshop.*$" manage=off
yabai -m rule --add app="Finder" title="^.*Info.*$" manage=off
yabai -m rule --add app="Calendar" space=9
yabai -m rule --add app="zoom.us" space=8

yabai -m rule --add app="^Spotify$" scratchpad=spotify grid=11:11:1:1:9:9

echo "yabai configuration loaded.."
