os:
  editPreset: 'nvim'
  open: 'code -r {{filename}}'
gui:
  nerdFontsVersion: '3'
  skipRewordInEditorWarning: true

[merge]
  tool = nvim
[mergetool "nvim"]
  cmd = nvim -f -c \"Gdiffsplit!\" \"$MERGED\"
[mergetool]
  prompt = false
